services:
  postgres:
    image: postgres:15-alpine
    container_name: post-example-container
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: post-example
